parameters:
    antqa.dataexporter.class: AntQa\Bundle\DataExporterBundle\Service\DataExporter

services:
    antqa.dataexporter:
        class: %antqa.dataexporter.class%
        public: true
        scope: prototype
        arguments:
          - %kernel.bundles%
          - '@templating'
          - '@?knp_snappy.pdf'
